---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# nycpalettes

<!-- badges: start -->
<!-- badges: end -->

Small R package that contains color palettes based on pictures that I
(and [Sharath Koorathota](https://github.com/schko)) took around NYC.

Created using the [colorfindr](https://github.com/zumbov2/colorfindr) package and heavily inspired by the [wesanderson](https://github.com/karthik/wesanderson) package.

## Installation

Development version on [GitHub](https://github.com/):

``` {r}
# install.packages("devtools")
devtools::install_github("kellycotton/nycpalettes")
```

## Example
```{r example, fig.height = 1.5}
library(nycpalettes)
library(ggplot2)

ggplot(mtcars, aes(mpg, disp, color = factor(gear))) + geom_point() +
  scale_color_manual(values = nyc_palette("DUMBO"))
```

